# This file is part of svgis.
# https://github.com/fitnr/svgis

# Licensed under the GNU General Public License v3 (GPLv3) license:
# http://opensource.org/licenses/GPL-3.0
# Copyright (c) 2015, Neil Freeman <contact@fakeisthenewreal.org>

language: python

python:
    - 2.7
    - 3.3
    - 3.4
    - 3.5

sudo: true

before_install:
    - sudo apt-get -qq update
    - sudo apt-get -qq install -y libgdal1-dev

install:
    - make
    - pip install fionautil>=0.3.1
    - python setup.py install

script:
    - make test
    - pip uninstall -y numpy
    - make test
