# This file is part of svgis.
# https://github.com/fitnr/svgis

# Licensed under the GNU General Public License v3 (GPLv3) license:
# http://opensource.org/licenses/GPL-3.0
# Copyright (c) 2015, Neil Freeman <contact@fakeisthenewreal.org>

language: python

python:
    - 2.7
    - 3.3
    - 3.4
    - 3.5

os:
 - linux

git:
  depth: 3

sudo: true

env:
  - NUMPY=yes
  - CLIP=yes
  - NUMPY= CLIP=

matrix:
  exclude:
    - python: 3.3
      env: NUMPY=yes
    - python: 3.3
      env: CLIP=yes
    - python: 3.4
      env: NUMPY=yes
    - python: 3.4
      env: CLIP=yes

cache:
  directories:
    - $HOME/.cache/pip

before_install:
    - if [[ $TRAVIS_OS_NAME == "linux" ]]; then sudo apt-get -qq update; fi
    - if [[ $TRAVIS_OS_NAME == "linux" ]]; then sudo apt-get -qq install -y libgdal1-dev; fi
    - pip install docutils coverage python-coveralls
    - if [[ $NUMPY == "yes" ]]; then pip install numpy; fi
    - if [[ $NUMPY != "yes" ]]; then pip uninstall -y numpy; fi

install:
    - make
    - python setup.py install
    - if [[ $CLIP == "yes" ]]; then pip install -e .[clip]; fi
    - if [[ $NUMPY == "yes" ]]; then pip install -e .[simplify]; fi

script:
    - make test QUIET= -W tests/test_data/cb_2014_us_nation_20m.zip

after_script:
  - svgis -h
  - svgis draw -h
  - svgis style -h
  - svgis scale -h
  - svgis project -h
  - svgis bounds -h
  - coveralls
  - make profile
  - pip list
