# This file is part of svgis.
# https://github.com/fitnr/svgis

# Licensed under the GNU General Public License v3 (GPLv3) license:
# http://opensource.org/licenses/GPL-3.0
# Copyright (c) 2016-7, Neil Freeman <contact@fakeisthenewreal.org>

language: python

python:
  - "3.6"
  - "3.7"
  - "3.8"

os:
  - linux

git:
  depth: 3

sudo: true

env:
 - EXTRAS=none
 - EXTRAS=numpy,clip,simplify

cache:
  directories:
    - $HOME/.cache/pip

before_install:
  - if [[ $TRAVIS_OS_NAME == "linux" ]]; then sudo apt-get -q update; fi
  - if [[ $TRAVIS_OS_NAME == "linux" ]]; then sudo apt-get -q install -y libgdal-dev ; fi
  - pip uninstall -y numpy visvalingamwyatt
  - pip install coverage[toml] flit

install:
  - flit install -s --deps develop --extras $EXTRAS

before_script:
  - fio --gdal-version || echo 'fio failed'
  - fio --version || echo 'fio failed'
  - fio info tests/test_data/cb_2014_us_nation_20m.json || echo 'fio failed'

script:
  - make test
  - make test-cli

after_failure:
  - echo $GDAL_DATA $PROJ_LIB
  - fio info --indent 2 tests/test_data/cb_2014_us_nation_20m.json
  - fio info --indent 2 tests/test_data/tl_2015_11_place.json
  - head tests/test_data/test.svg
  - unzip -l tests/test_data/zip.svg

after_script:
  - make coverage -o test
  - svgis -h
  - svgis draw -h
  - svgis style -h
  - svgis scale -h
  - svgis project -h
  - svgis bounds -h
  - make profile
