# This file is part of svgis.
# https://github.com/fitnr/svgis

# Licensed under the GNU General Public License v3 (GPLv3) license:
# http://opensource.org/licenses/GPL-3.0
# Copyright (c) 2016-7, Neil Freeman <contact@fakeisthenewreal.org>

language: python

python:
  - 3.6
  - 3.7
  - 3.8

os:
  - linux

git:
  depth: 3

sudo: true

env:
 - GDAL=gdal
 - GDAL=gdal1
 - GDAL=gdal EXTRAS=yes
 - GDAL=gdal1 EXTRAS=yes

matrix:
  exclude:
    - env: GDAL=gdal EXTRAS=yes
      python: 3.4

    - env: GDAL=gdal1 EXTRAS=yes
      python: 3.4

    - env: GDAL=gdal EXTRAS=yes
      python: 3.5

    - env: GDAL=gdal1 EXTRAS=yes
      python: 3.5

  allow_failures:
    - os: osx

  include:
    - language: generic
      os: osx
      env: PYTHON3
      before_install:
        - brew --version
        - brew install python gdal
        - virtualenv env -p python
        - source env/bin/activate

    - language: generic
      os: osx
      env: PYTHON
      before_install:
        - brew --version
        - brew install python3 gdal
        - virtualenv env -p python3
        - source env/bin/activate

cache:
  directories:
    - $HOME/.cache/pip

before_install:
    - pip install docutils coverage python-coveralls
    - if [[ $TRAVIS_OS_NAME == "linux" ]]; then sudo apt-get -q update; fi
    - if [[ $TRAVIS_OS_NAME == "linux" ]]; then sudo apt-get -q install -y lib${GDAL}-dev ; fi
    - if [[ $TRAVIS_PYTHON_VERSION != 3.6 ]]; then export GDAL_DATA=/usr/share/gdal/1.10 PROJ_LIB=/usr/share/proj ; fi
    - if [[ -z "$EXTRAS" ]]; then pip uninstall -y numpy visvalingamwyatt || :; fi

install:
    - python setup.py install
    - if [[ $EXTRAS == "yes" ]]; then pip install .[clip,simplify]; fi

before_script:
    - fio --version
    - fio --gdal-version
    - fio info tests/test_data/cb_2014_us_nation_20m.json

after_failure:
  - echo $GDAL_DATA $PROJ_LIB
  - fio info --indent 2 tests/test_data/cb_2014_us_nation_20m.json
  - fio info --indent 2 tests/test_data/tl_2015_11_place.json

script:
    - make test QUIET=

after_script:
  - svgis -h
  - svgis draw -h
  - svgis style -h
  - svgis scale -h
  - svgis project -h
  - svgis bounds -h
  - coveralls
  - make profile
