[build-system]
requires = ["flit_core<5"]
build-backend = "flit_core.buildapi"

[project]
name = "svgis"
authors = [
  {name = "Neil Freeman", email = "contact@fakeisthenewreal.org"}
]
keywords = ["svg", "gis", "geojson", 'shapefile', "cartography", "map", "geodata"]
license = "GPL-3.0-or-later"
classifiers = [
    "Intended Audience :: Developers",
    "Natural Language :: English",
    "Operating System :: Unix",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Operating System :: OS Independent",
]
readme = "README.md"
dynamic = ["description", "version"]
requires-python = ">=3.10"
dependencies = [
    "click>=8,<9",
    "pyproj>=2.6",
    "fiona>=1.8",
    "tinycss2>=1.0.2",
    "utm>=0.4.0,<1",
    "cssselect>=1.1.0",
    "lxml>=4.5.0",
]

[project.urls]
Repository = "https://github.com/fitnr/svgis"

[project.optional-dependencies]
numpy = ["numpy"]
clip = ["shapely>=1.5.7"]
simplify = ["visvalingamwyatt>=0.1.1"]
dev = [
    "coverage[toml]",
    "pylint>2.5.0"
]
doc = [
    "sphinx",
    "sphinx-rtd-theme"
]

[project.scripts]
svgis = "svgis.cli:main"

[tool.coverage.run]
branch = true
source = ["svgis"]

[tool.coverage.report]
exclude_lines = [
    "pragma: no cover",
    "def __repr__",
    "raise NotImplementedError",
    "if __name__ == .__main__.:",
    "except ImportError",
]

[tool.pylint.master]
fail-under = "9.5"

[tool.pylint.basic]
good-names = "f,g,i,j,k,x,y,z"

[tool.pylint.messages_control]
disable = "invalid-name"

[tool.pylint.format]
max-line-length = 120

[tool.ruff]
target-version = "py311"
line-length = 120

[tool.ruff.lint]
select = ["I", "E"]

[tool.ruff.format]
quote-style = "preserve"
